### ISSUE TITLE
`npmRegistry` is not passed in to `npm-registry-fetch`

### ISSUE THREAD

**Issue by mstergianis** [single-spa/self-hosted-shared-dependencies#13]
It appears `npmRegistry` doesn't do anything. Running with and without the option gave me the same error for a private package.

```
--> @vmware/some-private-lib
HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@vmware/some-private-lib - Not found
    at <project-dir>/node_modules/npm-registry-fetch/check-response.js:134:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildPackage (file:///<project-dir>/node_modules/self-hosted-shared-dependencies/lib/self-hosted-shared-dependencies.js:235:18)
    at async build (file:///<project-dir>/node_modules/self-hosted-shared-dependencies/lib/self-hosted-shared-dependencies.js:208:20)
    at async file:///<project-dir>/node_modules/self-hosted-shared-dependencies/bin/self-hosted-shared-dependencies-cli.js:29:9 {
  headers: [Object: null prototype] {
    date: [ 'Wed, 11 Aug 2021 20:46:42 GMT' ],
    'content-type': [ 'application/json' ],
    'content-length': [ '21' ],
    connection: [ 'keep-alive' ],
    'expect-ct': [
      'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
    ],
    vary: [ 'Accept-Encoding' ],
    server: [ 'cloudflare' ],
    'cf-ray': [ '67d450987ea7cab4-YYZ' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 404,
  code: 'E404',
  method: 'GET',
  uri: 'https://registry.npmjs.org/@vmware/some-private-lib',
  body: { error: 'Not found' },
  pkgid: 'some-private-lib'
}
```

**Comment by joeldenning** [comment]
Use `registryFetchOptions.registry` instead. See https://github.com/single-spa/self-hosted-shared-dependencies/releases/tag/v2.0.0
